# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
evm_version = "cancun"
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.24"
src = "src"
test = "test"
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'create3-factory/=lib/create3-factory/'
]

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY}" }
base = { key = "${ETHERSCAN_KEY}" }
